name: Go checks
on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  go-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: .go-version
          cache: true
      - name: go vet
        run: go vet ./...
      - name: go build
        run: go build ./...
      - name: Run tests
        run: go test ./...
